#!/usr/bin/env bash

br="$(git rev-parse --abbrev-ref HEAD)"
cf="${1}"

die() {
  printf "fatal: ${1}\n" "${2}" >&2
  printf "info: use '--no-verify' to disable this check\n"

  exit 1
}

verify_no_merge_master() {
  [ "$(cat "${cf}" | grep -ci "merge branch 'master'")" = "0" ] \
    || die "refusing to merge 'origin/master' into local branch '${br}'\
            \nuse 'git rebase master' instead\n"
}

verify_spelling() {
  sp="$(cat "${cf}" | aspell --list)"

  cn="$(echo ${sp} | wc -l)"
  for word in "${sp}"; do
    echo "${word}"
  done

  [ "${cn}" = "0" ] \
    || die "commit message contains ${cn} mispelled words\n"
}

main() {
  verify_no_merge_master
  verify_spelling
}

main
