type                                    = internal/battery
full-at                                 = 98
battery                                 = BAT0
adapter                                 = AC
poll-interval                           = 5

format-charging                         = <label-charging>
format-charging-padding                 = 0

format-charging-prefix                  = "  "
format-charging-prefix-background       = ${xrdb:color0}
format-charging-prefix-foreground       = ${xrdb:color4}
format-charging-prefix-padding 	        = 1

label-charging                          = "%percentage%% "
label-charging-background               = ${colors.background}
label-charging-foreground               = ${xrdb:color7}
label-charging-padding                  = 1

format-discharging                      = <label-discharging>
format-discharging-padding              = 0

format-discharging-prefix               = "   "
format-discharging-prefix-background    = ${colors.color0}
format-discharging-prefix-foreground    = ${colors.color4}
format-discharging-prefix-padding       = 0

label-discharging                       = "%percentage%% "
label-discharging-background            = ${colors.background}
label-discharging-foreground            = ${colors.color7}
label-discharging-padding               = 1

format-full                             = <label-full>
format-full-padding                     = 0

format-full-prefix                      = "   "
format-full-prefix-background           = ${colors.color0}
format-full-prefix-foreground           = ${colors.color4}
format-full-prefix-padding              = 0

label-full                              = "%percentage%% "
label-full-background                   = ${colors.background}
label-full-foreground                   = ${colors.color7}
label-full-padding                      = 1

label-disconnected                      = "disconnected"
label-disconnected-padding              = 1
