type                                  = internal/network

interface                             = wlp2s0

interval                              = 3.0
ping-interval                         = 3

format-connected                      = <label-connected>
format-connected-padding              = 0

format-connected-prefix               = 
format-connected-prefix-padding       = 2
format-connected-prefix-background    = ${colors.color0}
format-connected-prefix-foreground    = ${colors.color8}

label-connected                       = "%essid%"
label-connected-background            = ${colors.color2}
label-connected-foreground            = ${colors.color0}
label-connected-padding               = 3

format-disconnected                   = disconnected

format-disconnected-prefix            = 
format-disconnected-prefix-padding    = 2
format-disconnected-prefix-foreground = ${colors.color1}
