type                            = internal/xwindow
format                          = <label>

label                           = %title%
format-background               = ${colors.color0}
format-foreground               = ${colors.color8}
format-padding                  = 4

format-prefix                   = 
format-prefix-background        = ${colors.color1}
format-prefix-foreground        = ${colors.color0}
label-maxlen                    = 30

